// SPDX-License-Identifier: MIT

#define OQS_VERSION_TEXT "@OQS_VERSION_TEXT@"
#define OQS_COMPILE_BUILD_TARGET "@OQS_COMPILE_BUILD_TARGET@"
#define OQS_DIST_BUILD 1
#define OQS_DIST_X86_64_BUILD 1
#define OQS_DIST_X86_BUILD 1
#define OQS_DIST_ARM64_V8_BUILD 1
#define OQS_DIST_ARM32_V7_BUILD 1
#define OQS_DIST_PPC64LE_BUILD 1
#define OQS_DEBUG_BUILD 1
#define ARCH_X86_64 1
#define ARCH_ARM64v8 1
#define ARCH_ARM32v7 1
#define BUILD_SHARED_LIBS 1
#define OQS_BUILD_ONLY_LIB 1
#define OQS_OPT_TARGET "@OQS_OPT_TARGET@"
#define USE_SANITIZER "@USE_SANITIZER@"
#define CMAKE_BUILD_TYPE "@CMAKE_BUILD_TYPE@"

#define OQS_USE_OPENSSL 1
#define OQS_USE_AES_OPENSSL 1
#define OQS_USE_SHA2_OPENSSL 1
#define OQS_USE_SHA3_OPENSSL 1

#define OQS_USE_PTHREADS_IN_TESTS 1

#define OQS_USE_ADX_INSTRUCTIONS 1
#define OQS_USE_AES_INSTRUCTIONS 1
#define OQS_USE_AVX_INSTRUCTIONS 1
#define OQS_USE_AVX2_INSTRUCTIONS 1
#define OQS_USE_AVX512_INSTRUCTIONS 1
#define OQS_USE_BMI1_INSTRUCTIONS 1
#define OQS_USE_BMI2_INSTRUCTIONS 1
#define OQS_USE_PCLMULQDQ_INSTRUCTIONS 1
#define OQS_USE_VPCLMULQDQ_INSTRUCTIONS 1
#define OQS_USE_POPCNT_INSTRUCTIONS 1
#define OQS_USE_SSE_INSTRUCTIONS 1
#define OQS_USE_SSE2_INSTRUCTIONS 1
#define OQS_USE_SSE3_INSTRUCTIONS 1

#define OQS_USE_ARM_AES_INSTRUCTIONS 1
#define OQS_USE_ARM_SHA2_INSTRUCTIONS 1
#define OQS_USE_ARM_SHA3_INSTRUCTIONS 1
#define OQS_USE_ARM_NEON_INSTRUCTIONS 1

#define OQS_SPEED_USE_ARM_PMU 1

#define OQS_ENABLE_TEST_CONSTANT_TIME 1

#define OQS_ENABLE_SHA3_xkcp_low_avx2 1

#define OQS_ENABLE_KEM_NTRUPRIME 1
#define OQS_ENABLE_KEM_ntruprime_sntrup761 1
#define OQS_ENABLE_KEM_ntruprime_sntrup761_avx2 1

///// OQS_COPY_FROM_UPSTREAM_FRAGMENT_ADD_ALG_ENABLE_DEFINES_START

#define OQS_ENABLE_KEM_KYBER 1
#define OQS_ENABLE_KEM_kyber_512 1
#define OQS_ENABLE_KEM_kyber_512_aarch64 1

///// OQS_COPY_FROM_UPSTREAM_FRAGMENT_ADD_ALG_ENABLE_DEFINES_END
